name: Contexts
on: 
    - push
    - workflow_dispatch

jobs:
    echo-data:
        runs-on: ubuntu-latest
        steps:
            - name: show Info
              run: | 
                echo "Nombre del evento: ${{github.event_name}}"
                echo "Ref: ${{github.event_name}}" 

            - name: RetrieveVariable
              run: |
                echo "Nombre del evento: ${{vars.MY_VAR}}"
                echo "Ref: ${{vars.ORG_VAR}}" 